name: GitHubPagesへのGitHubActions経由でのVitePressのデプロイ

on:
  push:
    branches:
      - main

env:
  cache-version: v1

jobs:
  build-deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/yarn
          key: ${{ env.cache-version }}-${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ env.cache-version }}-${{ runner.os }}-node-
      - name: install
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: lint
        run: yarn docs:lint

      - name: build
        run: yarn docs:build

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.USUYUKI_GITHUB_TOKEN }}
          publish_dir: ./dist
